"""
repositories/base.py — абстрактні інтерфейси (Protocol) для всіх репозиторіїв.

Мета: Google Sheets є замінюваним бекендом.
Щоб перейти на SQL — достатньо реалізувати ці протоколи для нового бекенду.
"""
from __future__ import annotations

from datetime import date
from typing import List, Optional, Protocol, runtime_checkable

from app.models import (
    AttendanceRecord,
    AuditLog,
    Event,
    Group,
    Lead,
    Member,
    MessageTemplate,
    Payment,
    PaymentStatus,
    ReminderLog,
    Task,
    UserRole,
)


@runtime_checkable
class IUserRoleRepository(Protocol):
    def get_all(self) -> List[UserRole]: ...
    def get_by_telegram_id(self, telegram_id: int) -> Optional[UserRole]: ...
    def upsert(self, user_role: UserRole) -> None: ...


@runtime_checkable
class IMemberRepository(Protocol):
    def get_all(self) -> List[Member]: ...
    def get_by_id(self, member_id: str) -> Optional[Member]: ...
    def get_active(self) -> List[Member]: ...
    def get_by_group(self, group_id: str) -> List[Member]: ...
    def upsert(self, member: Member) -> None: ...
    def add(self, member: Member) -> None: ...


@runtime_checkable
class IPaymentRepository(Protocol):
    def get_all(self) -> List[Payment]: ...
    def get_by_member(self, member_id: str) -> List[Payment]: ...
    def get_by_period(self, period: str) -> List[Payment]: ...
    def get_by_status(self, status: PaymentStatus) -> List[Payment]: ...
    def get_current_period_payments(self) -> List[Payment]: ...
    def upsert(self, payment: Payment) -> None: ...
    def add(self, payment: Payment) -> None: ...


@runtime_checkable
class IGroupRepository(Protocol):
    def get_all(self) -> List[Group]: ...
    def get_by_id(self, group_id: str) -> Optional[Group]: ...
    def get_active(self) -> List[Group]: ...
    def get_by_coach(self, coach_telegram_id: int) -> List[Group]: ...
    def upsert(self, group: Group) -> None: ...


@runtime_checkable
class IAttendanceRepository(Protocol):
    def get_by_date(self, lesson_date: date) -> List[AttendanceRecord]: ...
    def get_by_group_date(self, group_id: str, lesson_date: date) -> List[AttendanceRecord]: ...
    def get_by_member(self, member_id: str) -> List[AttendanceRecord]: ...
    def get_member_last_n_days(self, member_id: str, days: int) -> List[AttendanceRecord]: ...
    def upsert(self, record: AttendanceRecord) -> None: ...
    def add(self, record: AttendanceRecord) -> None: ...


@runtime_checkable
class ILeadRepository(Protocol):
    def get_all(self) -> List[Lead]: ...
    def get_by_id(self, lead_id: str) -> Optional[Lead]: ...
    def get_by_status(self, status) -> List[Lead]: ...
    def get_trials_on_date(self, trial_date: date) -> List[Lead]: ...
    def upsert(self, lead: Lead) -> None: ...
    def add(self, lead: Lead) -> None: ...


@runtime_checkable
class IEventRepository(Protocol):
    def get_all(self) -> List[Event]: ...
    def get_by_id(self, event_id: str) -> Optional[Event]: ...
    def get_upcoming(self, days: int = 7) -> List[Event]: ...
    def get_today(self) -> List[Event]: ...
    def upsert(self, event: Event) -> None: ...
    def add(self, event: Event) -> None: ...


@runtime_checkable
class IMessageTemplateRepository(Protocol):
    def get_all(self) -> List[MessageTemplate]: ...
    def get_by_name(self, name: str) -> Optional[MessageTemplate]: ...
    def upsert(self, template: MessageTemplate) -> None: ...


@runtime_checkable
class ITaskRepository(Protocol):
    def get_all(self) -> List[Task]: ...
    def get_open(self) -> List[Task]: ...
    def add(self, task: Task) -> None: ...
    def upsert(self, task: Task) -> None: ...


@runtime_checkable
class IReminderLogRepository(Protocol):
    def add(self, log: ReminderLog) -> None: ...
    def get_recent(self, target_id: str, reminder_type, hours: int = 24) -> List[ReminderLog]: ...


@runtime_checkable
class IAuditLogRepository(Protocol):
    def add(self, log: AuditLog) -> None: ...


class Repositories:
    """
    Контейнер усіх репозиторіїв — передається в сервіси.
    Дозволяє легко замінити бекенд.
    """
    def __init__(
        self,
        users: IUserRoleRepository,
        members: IMemberRepository,
        payments: IPaymentRepository,
        groups: IGroupRepository,
        attendance: IAttendanceRepository,
        leads: ILeadRepository,
        events: IEventRepository,
        templates: IMessageTemplateRepository,
        tasks: ITaskRepository,
        reminder_log: IReminderLogRepository,
        audit_log: IAuditLogRepository,
    ) -> None:
        self.users = users
        self.members = members
        self.payments = payments
        self.groups = groups
        self.attendance = attendance
        self.leads = leads
        self.events = events
        self.templates = templates
        self.tasks = tasks
        self.reminder_log = reminder_log
        self.audit_log = audit_log
